<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>SimpleBluetooth</RootNamespace>
    <AssemblyName>SimpleBluetooth</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>annotations</Nullable>
    <NoWarn>$(NoWarn);CS8618;CS8625;CS8600;CS8601;CS8602;CS8603;CS8604</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Transport\CommandMessenger.Transport.Bluetooth\CommandMessenger.Transport.Bluetooth.csproj" />
    <ProjectReference Include="..\..\CommandMessenger\CommandMessenger.csproj" />
  </ItemGroup>
</Project>
