export enum LoopbackCommand {
  Acknowledge = 0,
  Error = 1,
  Echo = 2,
  EchoResult = 3,
  AddFloats = 4,
  AddFloatsResult = 5,
  EchoInt = 6,
  EchoIntResult = 7,
  EchoBool = 8,
  EchoBoolResult = 9,
  MultiArgs = 10,
  MultiArgsResult = 11,
  Ping = 12,
  Pong = 13,
  EchoInt16 = 14,
  EchoInt16Result = 15,
  EchoDouble = 16,
  EchoDoubleResult = 17,
  WhoAmI = 18,
  WhoAmIResult = 19,
  SetId = 20,
  SetIdResult = 21
}
