<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>CommandMessenger.Transport.Network</RootNamespace>
    <AssemblyName>CommandMessenger.Transport.Network</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CommandMessenger\CommandMessenger.csproj" />
  </ItemGroup>

</Project>
